name: docs

on:
  push:
    branches: [ master ]
    paths:
      - 'docs/generate.sh'
      - 'docs/*/generate.sh'
      - 'make/*/Config.in'
      - 'make/*/*.mk'
      - 'make/libs/*/Config.in'
      - 'make/libs/*/*.mk'
      - 'config/ui/patches.in'
      - 'docs/wiki/*/*.md'
      - 'docs/screenshots/*.png'
      - 'docs/screenshots/*.jpg'
      - 'docs/screenshots/*.gif'
  workflow_dispatch:

jobs:
  build:
    container:
      image: ubuntu:18.04
    runs-on: ubuntu-latest

    steps:

      - name: update
        run: apt-get -y update && apt-get -y upgrade && apt-get -y dist-upgrade

      - name: install
        run: |
          DEBIAN_FRONTEND=noninteractive apt-get -y install \
            git locales imagemagick

      - name: locale
        run: locale-gen en_US.utf8 && locale-gen de_DE.UTF-8 && update-locale

      - name: clone
        run: |
          umask 0022
          git config --global --add safe.directory $GITHUB_WORKSPACE
          git clone https://github.com/$GITHUB_REPOSITORY.git $GITHUB_WORKSPACE --branch $GITHUB_REF_NAME

      - name: generate
        run: docs/generate.sh

      - name: commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git status
          git config --global --add safe.directory $GITHUB_WORKSPACE
          git add .
          git config --local user.name github-actions
          git config --local user.email github-actions@github.com
          git commit -m "docs: automatic update" || exit 0
          git config --local credential.helper '!x() { echo "password=$GITHUB_TOKEN"; };x'
          git push origin $GITHUB_REF_NAME


