name: issue_stalled

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest

    steps:

      - name: release
        uses: actions/stale@v5.0.0
        with:
          stale-message: 'stalled'
          close-message: 'stalled'
          stale-label: 'stalled'
          labels-to-remove-when-unstale: 'stalled'
          exempt-labels: 'task'
          days-before-stale: 10
          remove-stale-when-updated: true
          enable-statistics: true


